---

- name: Install cURL
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - "curl"
    - "python-pycurl"
  tags:
    - jenkins


- name: Add Jenkins APT key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key id=D50582E6 state=present
  register: jenkins_repo_installed
  tags:
    - jenkins

- name: Add Jenkins APT repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes
  register: jenkins_repo_installed
  tags:
    - jenkins
